import About from "@/components/About";
import Banner from "@/components/Banner";
import Contact from "@/components/Contact";
import Experience from "@/components/Experience";
import Footer from "@/components/Footer";
import LeftSide from "@/components/LeftSide";
import LoadingScreen from "@/components/LoadingScreen";
import Meeting from "@/components/Meeting";
import Navbar from "@/components/Navbar";
import Projects from "@/components/Projects";
import RightSide from "@/components/RightSide";
import Services from "@/components/Services";
import Skills from "@/components/Skills";
import Head from "next/head";
import { motion } from "framer-motion";
import Archive from "@/components/Archive";

export default function Home() {
  return (
    <>
      <Head>
        <title>Faisal Bukhari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* make this icon rounded */}
        <link
          rel="icon"
          href="/assets/images/profile.png"
          className="rounded-full"
        />
      </Head>

      {/* Loading Screen */}
      <LoadingScreen />

      <main className="w-full min-h-screen font-bodyFont bg-bodyColor text-textLight overflow-x-hidden">
        <Navbar />
        <div className="w-full">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className="hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0 z-10"
          >
            <LeftSide />
          </motion.div>
          <div className="w-full">
            <Banner />
            <About />
            <Projects />
            <Archive />
            <Services />
            <Experience />
            <Skills />
            <Meeting />
            <Contact />
            <Footer />
          </div>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className="hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0 z-10"
          >
            <RightSide />
          </motion.div>
        </div>
      </main>
    </>
  );
}
